services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

      - Telegram__Enabled=${TELEGRAM_ENABLED:-false}
      - Telegram__Token=${TELEGRAM_TOKEN}
      - Telegram__WebhookUrl=${TELEGRAM_WEBHOOK_URL}

      - Max__Enabled=${MAX_ENABLED:-false}
      - Max__Token=${MAX_TOKEN}
      - Max__TimeoutSeconds=${MAX_TIMEOUT_SECONDS:-30}

      # api | inmemory | database
      - Data__Source=${DATA_SOURCE:-inmemory}
      - Data__ApiBaseUrl=${DATA_API_BASE_URL}
      - RefInfoApi__BaseUrl=${REFINFOAPI__BASEURL:-${DATA_API_BASE_URL}}
      - RefInfoApi__Username=${REFINFOAPI__USERNAME:-}
      - RefInfoApi__Password=${REFINFOAPI__PASSWORD:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8080"
