<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-HandbookBot-04799c9c-85fb-4bc3-9555-f193a0cc633c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HandbookBot.Core\HandbookBot.Core.csproj" />
    <ProjectReference Include="..\HandbookBot.Data\HandbookBot.Data.csproj" />
    <ProjectReference Include="..\HandbookBot.Telegram\HandbookBot.Telegram.csproj" />
    <ProjectReference Include="..\HandbookBot.Max\HandbookBot.Max.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
